/* Exercicio - Database para a Oficina do Sr José */

CREATE DATABASE OFICINA;

USE OFICINA;


CREATE TABLE PROPRIETARIO(
	IDPROPRIETARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROP VARCHAR(45),
    CPF CHAR(11),
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO CHAR(3) ,
    NUMERO VARCHAR(45),
    ID_PROPRIETARIO INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    PLACA VARCHAR(10) NOT NULL UNIQUE, 
    ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_COR INT,
    ID_CARRO INT,
    PRIMARY KEY (ID_CARRO,ID_COR)
);

--/--

/* CONSTRAINT */

-- Tabela Proprietario
ALTER TABLE PROPRIETARIO ADD CONSTRAINT FK_PROPRIETARIO_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

-- Tabela TELEFONE
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PROPRIETARIO
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(IDPROPRIETARIO);

-- Tabela CARRO
ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) REFERENCES MARCA(IDMARCA);

-- Tabela CARRO_COR

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR_CARRO_COR
FOREIGN KEY(ID_COR) REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO_CARRO_COR
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

/* INSERT INTO */

INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 1);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 2);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 3);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 4);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 5);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 2);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 3);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 5);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 4);
INSERT INTO CARRO VALUES(NULL, 'HJK1H596', 3);

INSERT INTO MARCA VALUES(NULL, 'Hyundai');
INSERT INTO MARCA VALUES(NULL, 'Audi');
INSERT INTO MARCA VALUES(NULL, 'Toyota');
INSERT INTO MARCA VALUES(NULL, 'Honda');
INSERT INTO MARCA VALUES(NULL, 'Nissan');

INSERT INTO COR VALUES(NULL, 'Branco');
INSERT INTO COR VALUES(NULL, 'Preto');
INSERT INTO COR VALUES(NULL, 'Azul');
INSERT INTO COR VALUES(NULL, 'Prata');
INSERT INTO COR VALUES(NULL, 'Azul');

INSERT INTO CARRO_COR VALUES(1, 1);
INSERT INTO CARRO_COR VALUES(2, 1);
INSERT INTO CARRO_COR VALUES(3, 1);
INSERT INTO CARRO_COR VALUES(4, 1);
INSERT INTO CARRO_COR VALUES(5, 1);
INSERT INTO CARRO_COR VALUES(1, 1);
INSERT INTO CARRO_COR VALUES(2, 1);
INSERT INTO CARRO_COR VALUES(3, 1);
INSERT INTO CARRO_COR VALUES(4, 1);
INSERT INTO CARRO_COR VALUES(5, 1);

INSERT INTO PROPRIETARIO VALUES(NULL, 'Ana', '12345678902', 1);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Maria', '12345678902', 2);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Andre', '12345678902', 3);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Jose', '12345678902', 4);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Gabreilli', '12345678902', 5);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Juliano', '12345678902', 6);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Adriana', '12345678902', 7);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Alisson', '12345678902', 8);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Mario', '12345678902', 9);
INSERT INTO PROPRIETARIO VALUES(NULL, 'Sandro', '12345678902', 10);

INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 1);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '4567635284', 1);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 2);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '4567635284', 3);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 5);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '4567635284', 6);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 7);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '4567635284', 8);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 8);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '4567635284', 10);
INSERT INTO TELEFONE VALUES(NULL, 'CEL', '4567635284', 9);
INSERT INTO TELEFONE VALUES(NULL, 'COM', '4567635284', 9);
INSERT INTO TELEFONE VALUES(NULL, 'RES', '4567635284', 9);


