/* ALTERANDO TABELAS */

USE PROJETO;

CREATE TABLE TABELA(
	COLUNA01 VARCHAR(30),
	COLUNA02 VARCHAR(30),
	COLUNA03 VARCHAR(30)
);

-- Como seria incluir a Primary Key junto a criação da tabela
CREATE TABLE TABELA(
	COLUNA1 INT PRIMARY KEY AUTO_INCREMENT
);

-- Adicionado a PK 
ALTER TABLE TABELA 
ADD PRIMARY KEY (COLUNA01);

-- Ao adicionar uma coluna, por padrão ela vai para a ultima posicao
ALTER TABLE TABELA 
ADD COLUNA04 varchar(30);

-- Adicionando uma coluna com posicao especifica
ALTER TABLE TABELA 
ADD COLUMN COLUNA05 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA03;

-- Modificando o tipo de campo
ALTER TABLE TABELA
 MODIFY COLUNA02 DATE NOT NULL;

-- Renomeando o nome da tabela
ALTER TABLE TABELA 
RENAME PESSOA;

CREATE TABLE TIME(
	IDTIME INT PRIMARY KEY AUTO_INCREMENT,
	TIME VARCHAR(30),
	ID_PESSOA VARCHAR(30)
);

-- Foreign key
ALTER TABLE TIME 
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA01);

/* VERIFICAR AS CHAVES */
SHOW CREATE TABLE TIME;