/* CONTINUAÇÃO DA AULA 19 - COMUNICAÇÃO COM BANCO 
	ADICIONANDO AO TRIGGER A AUTORIA DE UM EVENTO
*/

-- Trigger vai dizer: Quando um produto deletado, alterado e gravar o valor 
-- da alteração de preço

DROP DATABASE LOJA;

DROP DATABASE BACKUP;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES(NULL, 'LIVRO JAVA', 56.00);
INSERT INTO PRODUTO VALUES(NULL, 'LIVRO TABLEAU', 71.00);
INSERT INTO PRODUTO VALUES(NULL, 'LIVRO MY SQL', 69.00);
INSERT INTO PRODUTO VALUES(NULL, 'LIVRO C++', 53.00);

SELECT * FROM PRODUTO;

/*Nos diz QUANDO*/
SELECT NOW();
/*Nos diz QUEM*/
SELECT CURRENT_USER();

CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

USE LOJA;

SELECT * FROM PRODUTO;

DELIMITER #

-- Sempre que o proço for alterado vai acontecer a trigger
CREATE TRIGGER AUDI_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES
    (NULL,OLD.IDPRODUTO,OLD.NOME,
	OLD.VALOR,NEW.VALOR,NOW(),CURRENT_USER(),'U');
	
END
#

DELIMITER ;

UPDATE PRODUTO SET VALOR = 110.00
WHERE IDPRODUTO = 4;

SELECT * FROM PRODUTO;
SELECT * FROM BACKUP.BKP_PRODUTO;