/* PROCEDURES */

USE EMPRESA
GO

DROP TABLE TELEFONE
GO

CREATE TABLE PESSOA(
	IDPESSOA INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOT NULL CHECK (SEXO IN('M','F')), --ENUM
	MASCIMENTO DATE NOT NULL
)
GO

CREATE TABLE TELEFONE(
	IDTELEFONE INT NOT NULL IDENTITY,
	TIPO CHAR(3) NOT NULL CHECK ( TIPO IN('CEL','COM')),
	NUMERO CHAR(10) NOT NULL,
	ID_PESSOA INT
)
GO

ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
ON DELETE CASCADE
GO

INSERT INTO PESSOA VALUES('ANTONIO','M','1981-02-13')
INSERT INTO PESSOA VALUES('DANIEL','M','1985-03-18')
INSERT INTO PESSOA VALUES('CLEIDE','F','1979-10-13')
INSERT INTO PESSOA VALUES('MAFRA','M','1981-02-13')
GO

INSERT INTO TELEFONE VALUES('CEL','9879008',1)
INSERT INTO TELEFONE VALUES('COM','8757909',1)
INSERT INTO TELEFONE VALUES('CEL','9875890',2)
INSERT INTO TELEFONE VALUES('CEL','9347689',2)
INSERT INTO TELEFONE VALUES('COM','2998689',3)
INSERT INTO TELEFONE VALUES('COM','2098978',2)
INSERT INTO TELEFONE VALUES('CEL','9008679',3)
GO

/* CRIANDO A PROCEDURE */

CREATE PROC SOMA
AS
	SELECT 10 + 10 AS SOMA
GO

/* EXECUÇÃO DA PROCEDURE */

SOMA 

-- OU (mais recomentado por boas praticas)

EXEC SOMA
GO

/* PROCEDURE DINAMICA - COM PARAMETRO */

CREATE PROC CONTA @NUM1 INT, NUM2 INT
AS
	SELECT @NUM1 + @NUM2
GO

EXEC CONTA 90, 78
GO

/* APAGANDO PROCEDURE */

DROP PROC CONTA
GO

/* PROCEDURES EM TABELAS */

-- query que será usada na procedure
SELECT NOME, NUMERO 
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
WHERE TIPO = 'CEL'
GO

-- procedure
CREATE PROC TELEFONES @TIPO CHAR(3)
AS 
	SELECT NOME, NUMERO 
	FROM PESSOA
	INNER JOIN TELEFONE
	ON IDPESSOA = ID_PESSOA
	WHERE TIPO = 'CEL'
GO

EXEC TELEFONES 'CEL'
GO

EXEC TELEFONES 'COM'
GO

/*CRIANDO PROCEDURES COM PARAMETROS DE ENTRADA E SAIDA 
PARAMENTROS DE OUTPUT */

-- paramentro de saida onde a procedure vai responder algo

-- Criação
SELECT TIPO, COUNT(*) AS QUANTIDADE
FROM TELEFONE
GROUP BY TIPO
GO

CREATE PROC GETIPO @TIPO CHAR(3), @CONTADOR INT OUTPUT
AS
	SELECT @CONTADOR = COUNT(*)
	FROM TELEFONE
	WHERE TIPO = @TIPO
GO

/* EXECUCAO DA PROC COM PARAMENTRO DE DAIDA */
-- Transaction SQL -> Linguagem que o SQL server trabalha
-- Um bloco pode ser iniciado sem o "CREATE" podendo iniciar declarando

DECLARE @SAIDA INT
EXEC GETIPO @TIPO = 'CEL', @CONTADOR = @SAIDA OUTPUT
SELECT @SAIDA 
GO


-- Omitindo 
DECLARE @SAIDA INT
EXEC GETIPO 'CEL', @SAIDA OUTPUT
SELECT @SAIDA 
GO


/* PROCEDURE DE CADASTRO - INCLUINDO A REGRA DE NEGOCIO*/

SELECT @@IDENTITY -- Guarda o ultimo identity inserido na seção
GO

CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT

	INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO) -- gerar um id

	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE IDPESSOA = @@IDENTITY)

	INSERT INTO TELEFONE VALUES(@TIPO, @NUMERO, @FK)
GO

-- Executando
CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '98756321'
GO

-- Trazendo tudo de uma tabela com *

SELECT PESSOA.*, TELEFONE.*
FROM PESSOA
INNER JOIN TELEFONE
ON IDPESSOA = ID_PESSOA
GO

