/* Exercicio - Database para a Oficina do Sr José */

CREATE DATABASE OFICINA;

USE OFICINA;


CREATE TABLE PROPRIETARIO(
	IDPROPRIETARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROP VARCHAR(45),
    CPF CHAR(11),
	ID_CARRO INT UNIQUE
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO CHAR(3) ,
    NUMERO VARCHAR(45),
    ID_PROPRIETARIO INT
);

CREATE TABLE MARCA(
	IDMARCA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) UNIQUE
);

CREATE TABLE CARRO(
	IDCARRO INT PRIMARY KEY AUTO_INCREMENT,
    MARCA VARCHAR(45) NOT NULL,
    PLACA VARCHAR(10) NOT NULL UNIQUE, 
    ID_MARCA INT
);

CREATE TABLE COR(
	IDCOR INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) UNIQUE
);

CREATE TABLE CARRO_COR(
	ID_COR INT,
    ID_CARRO INT,
    PRIMARY KEY (ID_CARRO,ID_COR)
);

--/--

/* CONSTRAINT */

-- Tabela Proprietario
ALTER TABLE PROPRIETARIO ADD CONSTRAINT FK_PROPRIETARIO_CARRO
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

-- Tabela TELEFONE
ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_PROPRIETARIO
FOREIGN KEY(ID_PROPRIETARIO) REFERENCES PROPRIETARIO(IDPROPRIETARIO);

-- Tabela CARRO
ALTER TABLE CARRO ADD CONSTRAINT FK_CARRO_MARCA
FOREIGN KEY(ID_MARCA) REFERENCES MARCA(IDMARCA);

-- Tabela CARRO_COR

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_COR_CARRO_COR
FOREIGN KEY(ID_COR) REFERENCES COR(IDCOR);

ALTER TABLE CARRO_COR ADD CONSTRAINT FK_CARRO_CARRO_COR
FOREIGN KEY(ID_CARRO) REFERENCES CARRO(IDCARRO);

/* INSERT INTO */
